# Generated by Django 2.2.16 on 2020-10-04 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201004_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
